config/routes.rb
require 'api_constraints'

ISignin::Application.routes.draw do
  scope module: :web do
    match '/home',    to: 'static_pages#home',    via: :GET
    match '/help',    to: 'static_pages#help',    via: :GET
    match '/contact', to: 'static_pages#contact', via: :GET
    match '/about',   to: 'static_pages#about',   via: :GET
    match '/terms',   to: 'static_pages#terms',   via: :GET

    devise_for :users, controllers: { confirmations: 'web/users/confirmations',
                                      passwords: 'web/users/passwords',
                                      registrations: 'web/users/registrations',
                                      sessions: 'web/users/sessions' }

    scope module: :users do
      resources :users,   only: [:show, :index]
    end

    resources :events, only: [:show, :index, :create]

    root 'static_pages#home'

  end

  namespace :api, defaults: { format: 'json' } do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      devise_scope :user do
        post  'users/sign_up',  to: 'users/registrations#create'
        put   'users',          to: 'users/registrations#update'
        patch 'users',          to: 'users/registrations#update'
        post  'users/sign_in',  to: 'users/sessions#create'
        post  'users/password', to: 'users/passwords#create'
      end

      scope module: :users, constraints: {id: /\d+/} do
        resources :users, only: [:show, :index]
      end

      resources :events, only: [:show, :index, :create, :update], constraints: {id: /\d+/}
      match 'events/nearests', to: 'events/nearests#index', via: :GET

    end
  end
end

app/controllers/web/static_pages_controller.rb
class Web::StaticPagesController < Web::WebController
  skip_before_action :authenticate_user_with_token!

  def home
  end

  def help
  end

  def about
  end

  def contact
  end

  def terms

  end

end

app/views/web/static_pages/_feature_left.html.erb
<div class="row featurette">
  <div class="col-md-5">
    <%= image_tag image_title, class: 'featurette-image img-responsive center-block',
                                 alt: image_alt_title,
                               style: 'width: 350px; height: 350px' %>
  </div>
  <div class="col-md-7">
    <h2 class="featurette-heading">
      <%= feature_heading %>
      <span class="text-muted">
        <%= feature_subtitle %>
      </span>
    </h2>
    <p class="lead">
      <%= feature_description %>
    </p>
  </div>
</div>

app/views/web/static_pages/_feature_right.html.erb
<div class="row featurette">
  <div class="col-md-7">
    <h2 class="featurette-heading">
      <%= feature_heading %>
      <span class="text-muted">
        <%= feature_subtitle %>
      </span>
    </h2>
    <p class="lead">
      <%= feature_description %>
    </p>
  </div>
  <div class="col-md-5">
    <%= image_tag image_title, class: 'featurette-image img-responsive center-block',
                                 alt: image_alt_title,
                               style: 'width: 350px; height: 350px;' %>
  </div>
</div>

app/views/web/static_pages/_recommand.html.erb
<div class="col-lg-4" style="text-align: center;">
  <%= image_tag image_title, alt: image_alt_title,
                           class: 'img-circle',
                           style: 'width: 140px; height: 140px;' %>
  <h2><%= heading %></h2>
  <p><%= paragraph %></p>
  <p>
    <a class="btn btn-default" href="#" role="button">View details »</a>
  </p>
</div>

app/views/web/static_pages/_section_a.html.erb
<br>
<hr>
<br>
<% feature_heading  = t '.first_feature_heading' %>
<% feature_subtitle = t '.first_feature_subtitle' %>
<% feature_description = t '.first_feature_description' %>
<%= render partial: 'web/static_pages/feature_right',
           locals: {image_title: '300x300.png',
                    image_alt_title: '300x300',
                    feature_heading: feature_heading,
                    feature_subtitle: feature_subtitle,
                    feature_description: feature_description } %>
<br>
<hr>
<br>
<% feature_heading  = t '.second_feature_heading' %>
<% feature_subtitle = t '.second_feature_subtitle' %>
<% feature_description = t '.second_feature_description' %>
<%= render partial: 'web/static_pages/feature_left',
           locals: {image_title: '300x300.png',
                    image_alt_title: '300x300',
                    feature_heading: feature_heading,
                    feature_subtitle: feature_subtitle,
                    feature_description: feature_description } %>
<br>
<hr>
<br>
<% feature_heading  = t '.third_feature_heading' %>
<% feature_subtitle = t '.third_feature_subtitle' %>
<% feature_description = t '.third_feature_description' %>
<%= render partial: 'web/static_pages/feature_right',
           locals: {image_title: '300x300.png',
                    image_alt_title: '300x300',
                    feature_heading: feature_heading,
                    feature_subtitle: feature_subtitle,
                    feature_description: feature_description } %>
<br>
<hr>
<br>
<% feature_heading  = t '.fourth_feature_heading' %>
<% feature_subtitle = t '.fourth_feature_subtitle' %>
<% feature_description = t '.fourth_feature_description' %>
<%= render partial: 'web/static_pages/feature_left',
           locals: {image_title: '300x300.png',
                    image_alt_title: '300x300',
                    feature_heading: feature_heading,
                    feature_subtitle: feature_subtitle,
                    feature_description: feature_description } %>

app/views/web/static_pages/_section_b.html.erb
<h3>Section B</h3>
<br>
<div class="row">
  <% heading   = t '.first_heading' %>
  <% paragraph = t '.first_paragraph' %>
  <%= render partial: 'web/static_pages/recommand',
             locals: {image_title: '250x250.png',
                      image_alt_title: '250x250',
                      heading: heading,
                      paragraph: paragraph} %>

  <% heading   = t '.second_heading' %>
  <% paragraph = t '.second_paragraph' %>
  <%= render partial: 'web/static_pages/recommand',
             locals: {image_title: '250x250.png',
                      image_alt_title: '250x250',
                      heading: heading,
                      paragraph: paragraph} %>

  <% heading   = t '.third_heading' %>
  <% paragraph = t '.third_paragraph' %>
  <%= render partial: 'web/static_pages/recommand',
             locals: {image_title: '250x250.png',
                      image_alt_title: '250x250',
                      heading: heading,
                      paragraph: paragraph} %>
</div>

app/views/web/static_pages/_section_c.html.erb
<h3>Section C</h3>
<br>
<p>Vestibulum nec erat eu nulla rhoncus fringilla ut non neque. Vivamus nibh urna, ornare id gravida ut, mollis a magna. Aliquam porttitor condimentum nisi, eu viverra ipsum porta ut. Nam hendrerit bibendum turpis, sed molestie mi fermentum id. Aenean volutpat velit sem. Sed consequat ante in rutrum convallis. Nunc facilisis leo at faucibus adipiscing.</p>

app/views/web/static_pages/about.html.erb
<% title = t '.title' %>
<% provide(:title, title) %>
<h1><%= t '.heading' %></h1>
<p>
  <%= t '.paragraph' %>
</p>

app/views/web/static_pages/contact.html.erb
<% title = t '.title' %>
<% provide(:title, title) %>
<h1><%= t '.heading' %></h1>
<p>
  <%= t '.paragraph' %>
</p>

app/views/web/static_pages/help.html.erb
<% title = t '.title' %>
<% provide(:title, title) %>
<h1><%= t '.heading' %></h1>
<%= link_to (t '.forgot_your_password'), new_password_path(resource_name) %><br />
<%= link_to (t '.Didnt_receive_confirmation_instructions'), new_confirmation_path(resource_name) %><br />

app/views/web/static_pages/home.html.erb
<br>
<ul class="nav nav-pills nav-justified">
  <li role="presentation" class="active"><a href="#sectionA" data-toggle="tab"><%= t '.section_A' %></a></li>
  <li role="presentation"><a href="#sectionB" data-toggle="tab"><%= t '.section_B' %></a></li>
  <li role="presentation"><a href="#sectionC" data-toggle="tab"><%= t '.section_C' %></a></li>
</ul>
<br>
<div class="tab-content">
  <div id="sectionA" class="tab-pane fade in active">
    <%= render partial: 'section_a' %>
  </div>

  <div id="sectionB" class="tab-pane fade">
    <%= render partial: 'section_b' %>
  </div>

  <div id="sectionC" class="tab-pane fade">
    <%= render partial: 'section_c' %>
  </div>
</div>

app/views/web/static_pages/terms.html.erb
<% title = t '.title' %>
<% provide(:title, title) %>
<h1><%= t '.heading' %></h1>
<p>
  <%= t '.paragraph' %>
</p>