config/routes.rb
require 'api_constraints'

ISignin::Application.routes.draw do
  scope module: :web do
    match '/home',    to: 'static_pages#home',    via: :GET
    match '/help',    to: 'static_pages#help',    via: :GET
    match '/contact', to: 'static_pages#contact', via: :GET
    match '/about',   to: 'static_pages#about',   via: :GET
    match '/terms',   to: 'static_pages#terms',   via: :GET

    devise_for :users, controllers: { confirmations: 'web/users/confirmations',
                                      passwords: 'web/users/passwords',
                                      registrations: 'web/users/registrations',
                                      sessions: 'web/users/sessions' }

    scope module: :users do
      resources :users,   only: [:show, :index]
    end

    resources :events, only: [:show, :index, :create]

    root 'static_pages#home'

  end

  namespace :api, defaults: { format: 'json' } do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      devise_scope :user do
        post  'users/sign_up',  to: 'users/registrations#create'
        put   'users',          to: 'users/registrations#update'
        patch 'users',          to: 'users/registrations#update'
        post  'users/sign_in',  to: 'users/sessions#create'
        post  'users/password', to: 'users/passwords#create'
      end

      scope module: :users, constraints: {id: /\d+/} do
        resources :users, only: [:show, :index]
      end

      resources :events, only: [:show, :index, :create, :update], constraints: {id: /\d+/}
      match 'events/nearests', to: 'events/nearests#index', via: :GET

    end
  end
end

app/views/web/layouts/_carousel.html.erb
<div id="home-page-carousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="home-page-carousel" data-slide-to="0" class="active"></li>
    <li data-target="home-page-carousel" data-slide-to="1"></li>
    <li data-target="home-page-carousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="item bg bg1 active">
      <%= render partial: 'web/layouts/carousel_part', locals: {slide_title: (t '.first_slide_title'),
                                                             caption: (t '.first_slide_caption'),
                                                             description: (t '.first_slide_description'),
                                                             button: (t '.first_slide_button')} %>
    </div>
    <div class="item bg bg2">
      <%= render partial: 'web/layouts/carousel_part', locals: {slide_title: (t '.second_slide_title'),
                                                             caption: (t '.second_slide_caption'),
                                                             description: (t '.second_slide_description'),
                                                             button: (t '.second_slide_button')} %>
    </div>
    <div class="item bg bg3">
      <%= render partial: 'web/layouts/carousel_part', locals: {slide_title: (t '.third_slide_title'),
                                                             caption: (t '.third_slide_caption'),
                                                             description: (t '.third_slide_description'),
                                                             button: (t '.third_slide_button')} %>
    </div>
  </div>

  <a class="left carousel-control"
     href="#home-page-carousel"
     role="button"
     data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"
          aria-hidden="true"></span>
    <span class="sr-only"><%= t '.Previous' %></span>
  </a>
  <a class="right carousel-control" href="#home-page-carousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only"><%= t '.Next' %></span>
  </a>
</div>

app/views/web/layouts/_carousel_part.html.erb
<div class="container">
  <div class="carousel-caption">
    <h2>
      <span class="glyphicon glyphicon-heart" aria-hidden="true"></span><%= " #{caption}" %>
    </h2>
    <p><%= description %></p>
    <p>
      <a class="btn btn-primary btn-xl" href="#" role="button">
       <%= button %>
      </a>
    </p>
  </div>
</div>

app/views/web/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul id="function_links">
      <li><%= link_to (t '.home').to_s,    home_path %></li>
      <li><%= link_to (t '.help').to_s,    help_path %></li>
      <li><%= link_to (t '.about').to_s,   about_path %></li>
      <li><%= link_to (t '.contact').to_s, contact_path %></li>
      <li><%= link_to (t '.terms').to_s,   terms_path %></li>
      <br>
      <li><%= link_to (t '.top').to_s, '#' %></li>
      <br>
      <small>
        <b>© 2015 iSignin, Inc. All rights reserved.</b>
      </small>
    </ul>
  </nav>
</footer>

app/views/web/layouts/_header.html.erb
<!--Sign up modal from navbar-->
<%= render partial: 'web/users/registrations/signup_modal' %>

<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class="container">
    <% if user_signed_in? %>
      <div class="navbar-header">
        <button type="button"
                class="navbar-toggle collapsed"
                data-toggle="collapse"
                data-target="#signin-navbar"
                aria-expanded="false"
                aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'iSignin', root_path, id: 'logo', class: 'navbar-brand' %>
      </div>
      <div id="signin-navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
              <li><%= link_to (t '.Users'), users_path %></li>
              <li class="dropdown">
                <button id="account-btn"
                        type="button"
                        class="btn btn-primary dropdown-toggle"
                        data-toggle="dropdown"
                        aria-expanded="false">
                  <%= t '.Account' %>
                  <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to (t '.Profile'), user_path(current_user) %></li>
                  <li><%= link_to (t '.Settings'), edit_user_registration_path(current_user) %></li>
                  <li class="divider"></li>
                  <li><%= link_to (t '.Sign_out'), destroy_user_session_path, method: 'delete' %></li>
                </ul>
              </li>
          <% end %>
        </ul>
      </div>
    <% else %>
        <div class="navbar-header">
          <button type="button"
                  class="navbar-toggle collapsed"
                  data-toggle="collapse"
                  data-target="#navbar"
                  aria-expanded="false"
                  aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'iSignin', root_path, id: 'logo', class: 'navbar-brand' %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <%= form_for(:user, url: session_path(:user), html: { class: 'navbar-form navbar-right'} ) do |f| %>
              <div class="form-group">
                <%= f.email_field :email, placeholder: (t '.Email'), class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.password_field :password, placeholder: (t '.Password'), class: 'form-control' %>
              </div>
              <%= f.submit (t '.Sign_in'), class: 'btn btn-primary', id: 'Signin_btn' %>
              <button id="Signup_btn"
                      type="button"
                      class="btn btn-primary"
                      data-toggle="modal"
                      data-target="#signupModal">
                <%= t '.Signup' %>
              </button>
          <% end %>
        </div>
    <% end %>
  </div>
</nav>

app/views/web/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<script src="../../assets/js/ie8-responsive-file-warning.js"></script>
<![endif]-->

app/views/web/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <%= favicon_link_tag 'favicon.ico' %>
  <% %w(57 60 72 76 114 120 144 152 180).each do |s| %>
      <%= favicon_link_tag "apple-touch-icon-#{s}x#{s}.png", rel: 'apple-touch-icon', type: 'image/png', sizes: "#{s}x#{s}" %>
  <% end %>

  <% %w(16 32).each do |s| %>
      <%= favicon_link_tag "favicon-#{s}x#{s}.png", rel: 'icon', type: 'image/png', sizes: "#{s}x#{s}" %>
  <% end %>

  <title><%= full_title yield(:title) %></title>

  <!-- Custom Fonts -->
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

  <meta name="description" content="a sign in application">
  <meta name="author" content="Damon Yuan">
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= javascript_include_tag :application %>
  <%= csrf_meta_tags %>
  <%=  render 'web/layouts/shim' %>
</head>

<body>
  <!--Navbar-->
  <%= render 'web/layouts/header' %>

  <!--Carousel-->
  <% if controller_name == 'static_pages' && action_name == 'home' %>
    <%= render 'web/layouts/carousel' %>
  <% end %>

  <br>

  <!--Rest of the page-->
  <div class="container marketing">
    <%= render partial: 'web/shared/alert' %>
    <%= yield %>
    <%= render 'web/layouts/footer' %>
  </div>
</body>
</html>